### ISSUE TITLE
Idk how to use it lol

### ISSUE THREAD

**Issue by DeSn4ke** [domi-btnr/ClientModBadges-API#7]
Hello, well i'm writting cause actually there is no explaination file to explain how to use it so i'm pretty much lost with this even tho i wanna use it
 ^^'

**Comment by domi-btnr** [comment]
Hello,

I have a small documentation here: [Endpoints](https://github.com/domi-btnr/ClientModBadges-API#endpoints)

For Example:
To get my Badges, you would call `GET https://clientmodbadges-api.herokuapp.com/users/354191516979429376`

**Comment by DeSn4ke** [comment]
Hello, Dominik, thanks for your answer, well the thing is that in general
i’m not anything good at understanding how to use this cause it’s not like
a plugin you can add and when i saw it was called an api i was like how can
i use this ? In general i’m don’t have a lot of knowledge on this so that’s
why i don’t know how to use it lol

What i understood rn as a way to use is from downloading the the file,
extract it and then open a terminal inside the folder to run commands

**Comment by domi-btnr** [comment]
The API provides just the Information for the Plugins. Plugins call the API to get the Badges from the Users and show them then. If you want to have it inside Discord, then you need to use a Plugin. 
I have one for Vencord and one for Enmity:
- [Enmity (iOS Mod)](https://github.com/domi-btnr/Enmity-Stuff/blob/main/dist/GlobalBadges.js)
- [Vencord (Might be broken)](https://github.com/domi-btnr/Vencord-Plugins/blob/main/GlobalBadges/globalBadges.tsx)

But anyone can use the API, so might be that there are other Plugins for other Mods like Vendetta or BetterDiscord.
I know that [Wolfie](https://github.com/Wolfkid200444) has GlobalBadges for Replugged and Vendetta. He uses his own API tho.

**Comment by domi-btnr** [comment]
@DeSn4ke Can I close the issue?
